# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}

  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080 # no cambiar en prod